ratings:
  namespace: student48-bookinfo-dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  image: ghcr.io/62130500119/bookinfo-ratings
  tag: dev
ingress:
  host: sitkmutt.bookinfo.dev.opsta.net
  path: "/student48/ratings(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-dev-ratings-mongodb:27017/ratings
  MONGO_DB_USERNAME: ratings
  COMMIT_SHA: CHANGME
extraEnvSecret:
  MONGO_DB_PASSWORD:
    bookinfo-dev-ratings-mongodb-secret: mongodb-password